# Generated by Django 2.2.4 on 2020-07-09 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.TextField(max_length=1000)),
                ('a1', models.CharField(max_length=100)),
                ('q2', models.TextField(max_length=1000)),
                ('a2', models.CharField(max_length=100)),
                ('q3', models.TextField(max_length=1000)),
                ('a3', models.CharField(max_length=100)),
                ('q4', models.TextField(max_length=1000)),
                ('a4', models.CharField(max_length=100)),
                ('q5', models.TextField(max_length=1000)),
                ('a5', models.CharField(max_length=100)),
                ('q6', models.TextField(max_length=1000)),
                ('a6', models.CharField(max_length=100)),
                ('q7', models.TextField(max_length=1000)),
                ('a7', models.CharField(max_length=100)),
                ('q8', models.TextField(max_length=1000)),
                ('a8', models.CharField(max_length=100)),
                ('q9', models.TextField(max_length=1000)),
                ('a9', models.CharField(max_length=100)),
                ('q10', models.TextField(max_length=1000)),
                ('a10', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('createdOn', models.DateField(default=django.utils.timezone.now)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questionBank', models.ManyToManyField(blank=True, to='api.Question')),
            ],
        ),
    ]
