# Generated by Django 2.2.4 on 2020-07-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questionBank',
        ),
        migrations.AddField(
            model_name='quiz',
            name='a1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='a10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='a2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='a3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='a4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='a5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='a6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='a7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='a8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='a9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q1',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q10',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q3',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q4',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q5',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q6',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q7',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q8',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q9',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
